kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: nodejs-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        name: nodejs-app
        image: fffeeeeeee/nodejs-app:latest
        ports:
        - containerPort: 3000