kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
  namespace: nodejs-namespace
spec:
  replicas: 3
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer